src/country_workspace/config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import debug_toolbar

from country_workspace.workspaces.sites import workspace

urlpatterns = [
    path(r"admin/", admin.site.urls),
    path(r"security/", include("unicef_security.urls", namespace="security")),
    path(r"social/", include("social_django.urls", namespace="social")),
    path(r"accounts/", include("django.contrib.auth.urls")),
    path(r"adminactions/", include("adminactions.urls")),
    path(r"sentry_debug/", lambda _: 1 / 0),
    path(r"__debug__/", include(debug_toolbar.urls)),
    path(r"", workspace.urls),
]

admin.site.site_header = "Workspace Admin"
admin.site.site_title = "Workspace Admin Portal"
admin.site.index_title = "Welcome to HOPE Workspace"

src/country_workspace/models/program.py
from typing import TYPE_CHECKING, Union

from django.db import models
from django.db.models import QuerySet
from django.utils.translation import gettext as _

from hope_flex_fields.models import DataChecker
from strategy_field.fields import StrategyField
from strategy_field.utils import fqn

from ..validators.registry import NoopValidator, beneficiary_validator_registry
from .base import BaseModel, Validable
from .office import Office

if TYPE_CHECKING:
    from .household import Household
    from .individual import Individual


class Program(BaseModel):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    FINISHED = "FINISHED"
    STATUS_CHOICE = (
        (ACTIVE, _("Active")),
        (DRAFT, _("Draft")),
        (FINISHED, _("Finished")),
    )
    CHILD_PROTECTION = "CHILD_PROTECTION"
    EDUCATION = "EDUCATION"
    HEALTH = "HEALTH"
    MULTI_PURPOSE = "MULTI_PURPOSE"
    NUTRITION = "NUTRITION"
    SOCIAL_POLICY = "SOCIAL_POLICY"
    WASH = "WASH"
    SECTOR_CHOICE = (
        (CHILD_PROTECTION, _("Child Protection")),
        (EDUCATION, _("Education")),
        (HEALTH, _("Health")),
        (MULTI_PURPOSE, _("Multi Purpose")),
        (NUTRITION, _("Nutrition")),
        (SOCIAL_POLICY, _("Social Policy")),
        (WASH, _("WASH")),
    )
    hope_id = models.CharField(max_length=200, unique=True, editable=False)
    country_office = models.ForeignKey(Office, on_delete=models.CASCADE, related_name="programs")
    name = models.CharField(max_length=255)
    programme_code = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, db_index=True)
    sector = models.CharField(max_length=50, choices=SECTOR_CHOICE, db_index=True)
    active = models.BooleanField(default=False)

    # Local Fields
    beneficiary_validator = StrategyField(
        registry=beneficiary_validator_registry, default=fqn(NoopValidator), blank=True, null=True
    )
    household_checker = models.ForeignKey(
        DataChecker, blank=True, null=True, on_delete=models.CASCADE, related_name="+"
    )

    individual_checker = models.ForeignKey(
        DataChecker, blank=True, null=True, on_delete=models.CASCADE, related_name="+"
    )

    household_search = models.TextField(default="name", help_text="Fields to use for searches")
    individual_search = models.TextField(default="name", help_text="Fields to use for searches")
    household_columns = models.TextField(default="name\nid", help_text="Columns to display ib the Admin table")
    individual_columns = models.TextField(default="name\nid", help_text="Columns to display ib the Admin table")
    extra_fields = models.JSONField(default=dict, blank=True, null=False)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("Programme")
        verbose_name_plural = _("Programmes")

    @property
    def households(self) -> "QuerySet[Household]":
        from country_workspace.models import Household

        return Household.objects.filter(batch__program=self)

    @property
    def individuals(self) -> "QuerySet[Individual]":
        from country_workspace.models import Individual

        return Individual.objects.filter(batch__program=self)

    def get_checker_for(self, m: Union[type[Validable], Validable]) -> DataChecker:
        from country_workspace.models import Household, Individual
        from country_workspace.workspaces.models import CountryHousehold, CountryIndividual

        if isinstance(m, (Household, CountryHousehold)) or m in (Household, CountryHousehold):
            return self.household_checker
        elif isinstance(m, (Individual, CountryIndividual)) or m in (Individual, CountryIndividual):
            return self.individual_checker
        else:
            raise ValueError(m)

src/country_workspace/workspaces/models.py
from typing import cast

from django.db import models
from django.utils.functional import cached_property

from hope_flex_fields.models import DataChecker

from country_workspace.models import AsyncJob, Batch, Household, Individual, Office, Program

__all__ = ["CountryProgram", "CountryHousehold", "CountryIndividual", "CountryBatch"]


class CountryBatch(Batch):
    class Meta:
        proxy = True
        verbose_name = "Country Batch"
        verbose_name_plural = "Country Batches"


class CountryHousehold(Household):
    class Meta:
        proxy = True
        verbose_name = "Country Household"
        verbose_name_plural = "Country Households"

    @cached_property
    def program(self) -> "CountryProgram":
        return cast(CountryProgram, self.batch.program)

    @cached_property
    def country_office(self) -> "DataChecker":
        return self.batch.program.country_office


class CountryIndividual(Individual):
    class Meta:
        proxy = True


class CountryProgram(Program):
    class Meta:
        proxy = True


class CountryChecker(DataChecker):
    country_office = models.ForeignKey(Office, on_delete=models.CASCADE)


class CountryJob(AsyncJob):
    class Meta:
        proxy = True

    # class Meta:
    #     app_label = "workspaces"

src/country_workspace/workspaces/admin/forms.py
from pathlib import Path

from django import forms
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext as _


@deconstructible
class ValidatableFileValidator(object):
    error_messages = {"invalid_file": _("Unsupported file format '%s'")}

    def __call__(self, f: Path) -> None:
        if Path(f.name).suffix not in [".xlsx"]:
            raise ValidationError(self.error_messages["invalid_file"] % Path(f.name).suffix)


class ImportFileForm(forms.Form):
    batch_name = forms.CharField(required=False, help_text="Label for this batch")

    check_before = forms.BooleanField(required=False, help_text="Prevent import if errors")
    pk_column_name = forms.CharField(
        required=True,
        initial="household_id",
        help_text="Which column contains the unique identifier of the record." "It is mandatory from Master/detail",
    )

    description_column_name = forms.CharField(required=False, initial="")

    first_line = forms.IntegerField(required=True, initial=0, help_text="First line to process")
    fail_if_alien = forms.BooleanField(required=False)
    file = forms.FileField(validators=[ValidatableFileValidator()])

src/country_workspace/workspaces/forms.py
from typing import TYPE_CHECKING

from django import forms
from django.contrib.admin.forms import AdminAuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from . import models
from .config import conf

if TYPE_CHECKING:
    from typing import Any

    from django.contrib.auth.base_user import AbstractBaseUser


class TenantAuthenticationForm(AdminAuthenticationForm):
    def confirm_login_allowed(self, user: "AbstractBaseUser") -> None:
        if not user.is_active:  # pragma: no cover
            raise ValidationError(self.error_messages["inactive"], code="inactive")


class SelectTenantForm(forms.Form):
    tenant = forms.ModelChoiceField(
        label=_("Office"),
        queryset=None,
        required=True,
        blank=False,
        limit_choices_to={"active": True},
    )
    next = forms.CharField(required=False, widget=forms.HiddenInput)

    def __init__(self, *args: "Any", **kwargs: "Any") -> None:
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["tenant"].queryset = conf.auth.get_allowed_tenants(self.request)


class ProgramForm(forms.ModelForm):
    class Meta:
        model = models.CountryProgram
        fields = ("country_office", "name")

src/country_workspace/web/templates/workspace/includes/fieldset.html
<fieldset class="module aligned {{ fieldset.classes }}">
    {% if fieldset.name %}<h2>{{ fieldset.name }}</h2>{% endif %}
    {% if fieldset.description %}
        <div class="description">{{ fieldset.description|safe }}</div>
    {% endif %}
    {% for line in fieldset %}
        <div class="form-row{% if line.fields|length == 1 and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
            {% if line.fields|length == 1 %}{{ line.errors }}{% else %}<div class="flex-container form-multiline">{% endif %}
            {% for field in line %}
                <div>
                    {% if not line.fields|length == 1 and not field.is_readonly %}{{ field.errors }}{% endif %}
                        <div class="flex-container{% if not line.fields|length == 1 %} fieldBox{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}{% elif field.is_checkbox %} checkbox-row{% endif %}">
                            {% if field.is_checkbox %}
                                {{ field.field }}{{ field.label_tag }}
                            {% else %}
                                {{ field.label_tag }}
                                {% if field.is_readonly %}
                                    <div class="readonly">{{ field.contents }}</div>
                                {% else %}
                                    {{ field.field }}
                                {% endif %}
                            {% endif %}
                        </div>
                    {% if field.field.help_text %}
                        <div class="help"{% if field.field.id_for_label %} id="{{ field.field.id_for_label }}_helptext"{% endif %}>
                            <div>{{ field.field.help_text|safe }}</div>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            {% if not line.fields|length == 1 %}</div>{% endif %}
        </div>
    {% endfor %}
</fieldset>

src/country_workspace/web/templates/workspace/includes/flex_field_form.html
{% if has_change_permission %}
    {% for field in form %}
        <tr>
            <th>{{ field.label }}</th>
            <th>{{ field }}
                <br>
            <span class="helptext">{{ field.field.flex_field.attrs.help_text }}</span>
            </th>
            <th>
                {% if perms.hope_flex_fields.can_change_flexfield %}

                    <a target="_admin" href="{% url "admin:hope_flex_fields_flexfield_change" field.field.flex_field.pk %}">
                    Rules
{#                    {{ field.field.flex_field.name }} ({{ field.field.flex_field.field.name }})#}
                {% endif %}
                </a>
            </th>
        </tr>
    {% endfor %}
    {#    {{ form.as_table }}#}
{% else %}
    {% for k,v in fields.items %}
        <tr>
            <th>{{ k }}</th>
            <td>{{ v }}</td>
        </tr>
    {% endfor %}
{% endif %}

src/country_workspace/web/templates/workspace/includes/object_delete_summary.html
{% load i18n %}
<h2>{% translate "Summary" %}</h2>
<ul>
    {% for model_name, object_count in model_count %}
    <li>{{ model_name|capfirst }}: {{ object_count }}</li>
    {% endfor %}
</ul>

src/country_workspace/web/templates/workspace/includes/program_title.html
{% load workspace_urls %}<h1>
    {% if program %}
    {%  url "workspace:workspaces_countryprogram_change" program.pk as purl %}
    &rsaquo; <a href="{{ purl }}">{{ program }}</a>

{#       &rsaquo;  <a href="{% url "workspace:workspaces_countryprogram_change" program.pk %}">{{ program }}</a>#}

        {% if perms.country_workspace.change_program %}
            <a class="icon icon-cogs small" target="_admin"
               href="{% url "admin:country_workspace_program_change" program.pk %}"></a>
        {% endif %}
        {% if household %}
{#          &rsaquo;   <a href="{% url "workspace:workspaces_countryhousehold_change" household.pk %}">{{ household }}</a>#}
    {%  url "workspace:workspaces_countryhousehold_change" household.pk as hurl %}
    &rsaquo; <a href="{{ hurl }}?batch__program__exact={{ program.pk }}">{{ household }}</a>


            {% if perms.country_workspace.change_household %}
                <a class="icon icon-cogs small" target="_admin"
                   href="{% url "admin:country_workspace_household_change" household.pk %}"></a>
            {% endif %}

        {% endif %}
        {% else %}
        <h1>&nbsp;</h1>
    {% endif %}
</h1>