src/country_workspace/config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import debug_toolbar

from country_workspace.workspaces.sites import workspace

urlpatterns = [
    path(r"admin/", admin.site.urls),
    path(r"security/", include("unicef_security.urls", namespace="security")),
    path(r"social/", include("social_django.urls", namespace="social")),
    path(r"accounts/", include("django.contrib.auth.urls")),
    path(r"adminactions/", include("adminactions.urls")),
    path(r"sentry_debug/", lambda _: 1 / 0),
    path(r"__debug__/", include(debug_toolbar.urls)),
    path(r"", workspace.urls),
]

admin.site.site_header = "Workspace Admin"
admin.site.site_title = "Workspace Admin Portal"
admin.site.index_title = "Welcome to HOPE Workspace"

src/country_workspace/models/base.py
from typing import TYPE_CHECKING, Any

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext as _

if TYPE_CHECKING:
    from hope_flex_fields.models import DataChecker


class BaseQuerySet(models.QuerySet["models.Model"]):

    def get(self, *args: Any, **kwargs: Any) -> "models.Model":
        try:
            return super().get(*args, **kwargs)
        except self.model.DoesNotExist:
            raise self.model.DoesNotExist(
                "%s matching query does not exist. Using %s %s" % (self.model._meta.object_name, args, kwargs)
            )


class BaseManager(models.Manager["models.Model"]):
    _queryset_class = BaseQuerySet


class Validable(models.Model):
    batch = models.ForeignKey("Batch", on_delete=models.CASCADE)
    last_checked = models.DateTimeField(default=None, null=True, blank=True)
    errors = models.JSONField(default=dict, blank=True, editable=False)
    flex_fields = models.JSONField(default=dict, blank=True)
    flex_files = models.BinaryField(null=True, blank=True)

    name = models.CharField(_("Name"), max_length=255)
    removed = models.BooleanField(_("Removed"), default=False)
    history = models.JSONField(default=dict, blank=True, editable=False)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.name or "%s %s" % (self._meta.verbose_name, self.id)

    @cached_property
    def checker(self) -> "DataChecker":
        raise NotImplementedError

    def validate_with_checker(self) -> bool:
        errors = self.checker.validate([self.flex_fields])
        if errors:
            self.errors = errors[1]
        else:
            self.errors = {}
        self.last_checked = timezone.now()
        self.save(update_fields=["last_checked", "errors"])
        return not bool(errors)


class BaseModel(models.Model):
    last_modified = models.DateTimeField(auto_now=True, editable=False)

    objects = BaseManager()

    class Meta:
        abstract = True

    def get_change_url(self, namespace: str = "workspace") -> str:
        return reverse(
            "%s:%s_%s_change" % (namespace, self._meta.app_label, self._meta.model_name),
            args=[self.pk],
        )

src/country_workspace/workspaces/models.py
from typing import cast

from django.db import models
from django.utils.functional import cached_property

from hope_flex_fields.models import DataChecker

from country_workspace.models import AsyncJob, Batch, Household, Individual, Office, Program

__all__ = ["CountryProgram", "CountryHousehold", "CountryIndividual", "CountryBatch"]


class CountryBatch(Batch):
    class Meta:
        proxy = True
        verbose_name = "Country Batch"
        verbose_name_plural = "Country Batches"


class CountryHousehold(Household):
    class Meta:
        proxy = True
        verbose_name = "Country Household"
        verbose_name_plural = "Country Households"

    @cached_property
    def program(self) -> "CountryProgram":
        return cast(CountryProgram, self.batch.program)

    @cached_property
    def country_office(self) -> "DataChecker":
        return self.batch.program.country_office


class CountryIndividual(Individual):
    class Meta:
        proxy = True


class CountryProgram(Program):
    class Meta:
        proxy = True


class CountryChecker(DataChecker):
    country_office = models.ForeignKey(Office, on_delete=models.CASCADE)


class CountryJob(AsyncJob):
    class Meta:
        proxy = True

    # class Meta:
    #     app_label = "workspaces"

src/country_workspace/workspaces/admin/forms.py
from pathlib import Path

from django import forms
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext as _


@deconstructible
class ValidatableFileValidator(object):
    error_messages = {"invalid_file": _("Unsupported file format '%s'")}

    def __call__(self, f: Path) -> None:
        if Path(f.name).suffix not in [".xlsx"]:
            raise ValidationError(self.error_messages["invalid_file"] % Path(f.name).suffix)


class ImportFileForm(forms.Form):
    batch_name = forms.CharField(required=False, help_text="Label for this batch")

    check_before = forms.BooleanField(required=False, help_text="Prevent import if errors")
    pk_column_name = forms.CharField(
        required=True,
        initial="household_id",
        help_text="Which column contains the unique identifier of the record." "It is mandatory from Master/detail",
    )

    description_column_name = forms.CharField(required=False, initial="")

    first_line = forms.IntegerField(required=True, initial=0, help_text="First line to process")
    fail_if_alien = forms.BooleanField(required=False)
    file = forms.FileField(validators=[ValidatableFileValidator()])

src/country_workspace/workspaces/forms.py
from typing import TYPE_CHECKING

from django import forms
from django.contrib.admin.forms import AdminAuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from . import models
from .config import conf

if TYPE_CHECKING:
    from typing import Any

    from django.contrib.auth.base_user import AbstractBaseUser


class TenantAuthenticationForm(AdminAuthenticationForm):
    def confirm_login_allowed(self, user: "AbstractBaseUser") -> None:
        if not user.is_active:  # pragma: no cover
            raise ValidationError(self.error_messages["inactive"], code="inactive")


class SelectTenantForm(forms.Form):
    tenant = forms.ModelChoiceField(
        label=_("Office"),
        queryset=None,
        required=True,
        blank=False,
        limit_choices_to={"active": True},
    )
    next = forms.CharField(required=False, widget=forms.HiddenInput)

    def __init__(self, *args: "Any", **kwargs: "Any") -> None:
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields["tenant"].queryset = conf.auth.get_allowed_tenants(self.request)


class ProgramForm(forms.ModelForm):
    class Meta:
        model = models.CountryProgram
        fields = ("country_office", "name")

src/hope_country_workspace/web/templates/workspace/app_index.html
{% extends "workspace/index.html" %}
{% load i18n %}

{% block bodyclass %}{{ block.super }} app-{{ app_label }}{% endblock %}

{% if not is_popup %}
{% block nav-breadcrumbs %}
  <nav aria-label="{% translate 'Breadcrumbs' %}">
    <div class="breadcrumbs">
      <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
      &rsaquo;
      {% for app in app_list %}
        {{ app.name }}
      {% endfor %}
    </div>
  </nav>
{% endblock %}
{% endif %}

{% block sidebar %}{% endblock %}

src/hope_country_workspace/web/templates/workspace/base.html
{% extends "~admin/layout.html" %}{% load i18n static %}
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'admin/hr.css' %}">
{% endblock %}

{% block userlinks %}
{#    {% if active_tenant %}#}
        {% block select_ba_form %}
            <div style="display: inline-flex">
                <form id="select-tenant" method="post" action="{% url "admin:select_tenant" %}">
                    {% csrf_token %}{{ tenant_form }}
                    <script>
                        document.querySelector('#id_tenant').addEventListener('change', function () {
                            document.getElementById('select-tenant').submit();
                        });
                    </script>
                </form>
            </div>
        {% endblock %}
        <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
            {% csrf_token %}
            <button type="submit">{% translate 'Logout' %}</button>
        </form>
        {% include "admin/color_theme_toggle.html" %}
{#    {% else %}#}
{#        {{ block.super }}#}
{#    {% endif %}#}
{% endblock %}
{% block footer %}{% include "workspace/_footer.html" %}{% endblock %}

src/hope_country_workspace/web/templates/workspace/change_list.html
{% extends "workspace/base_site.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "admin/css/changelists.css" %}">
  {% if cl.formset %}
    <link rel="stylesheet" href="{% static "admin/css/forms.css" %}">
  {% endif %}
  {% if cl.formset or action_form %}
    <script src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
<script src="{% static 'admin/js/filters.js' %}" defer></script>
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
        <ul class="object-tools">
          {% block object-tools-items %}
            {% change_list_object_tools %}
          {% endblock %}
        {% include "admin_extra_buttons/includes/change_list_buttons.html" %}
        </ul>
    {% endblock %}
    {% if cl.formset and cl.formset.errors %}
        <p class="errornote">
        {% blocktranslate count counter=cl.formset.total_error_count %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      <div class="changelist-form-container">
        {% block search %}{% search_form cl %}{% endblock %}
        {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}

        <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
        {% if cl.formset %}
          <div>{{ cl.formset.management_form }}</div>
        {% endif %}

        {% block result_list %}
          {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
        {% endblock %}
        {% block pagination %}{% pagination cl %}{% endblock %}
        </form>
      </div>
      {% block filters %}
        {% if cl.has_filters %}
          <nav id="changelist-filter" aria-labelledby="changelist-filter-header">
            <h2 id="changelist-filter-header">{% translate 'Filter' %}</h2>
            {% if cl.is_facets_optional or cl.has_active_filters %}<div id="changelist-filter-extra-actions">
              {% if cl.is_facets_optional %}<h3>
                {% if cl.add_facets %}<a href="{{ cl.remove_facet_link }}" class="hidelink">{% translate "Hide counts" %}</a>
                {% else %}<a href="{{ cl.add_facet_link }}" class="viewlink">{% translate "Show counts" %}</a>{% endif %}
              </h3>{% endif %}
              {% if cl.has_active_filters %}<h3>
                <a href="{{ cl.clear_all_filters_qs }}">&#10006; {% translate "Clear all filters" %}</a>
              </h3>{% endif %}
            </div>{% endif %}
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </nav>
        {% endif %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

src/hope_country_workspace/web/templates/workspace/index.html
{% extends "workspace/base_site.html" %}
{% load i18n static  %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}
{% block nav-sidebar %}{% include "~admin/nav_sidebar.html" %}{% endblock %}

{% block content %}
    <div id="content-main">
            {% include "workspace/_app_list.html" %}
    </div>
{% endblock %}

{% block sidebar %}{% include "workspace/_actionlist.html" %}{% endblock %}